### ISSUE TITLE
Use clean-css instead of csswring

### ISSUE THREAD

**Issue by marvinroger** [iamvdo/pleeease#24]
Pretty simple to implement, I would suggest you to use [Clean-css](https://github.com/jakubpawlowicz/clean-css) which is, [according to benchmarks](http://goalsmashers.github.io/css-minification-benchmark/), the most efficient css compressor.

Is there any reason why you use csswring?

**Comment by EightArmCode** [comment]
I'm looking at csswring over clean-css because of the bloat, and also because I am looking for a program that concatenates sourcemaps to the file, instead of creating a new one.
