### ISSUE TITLE
sourceMappingURL removed

### ISSUE THREAD

**Issue by christianseel** [iamvdo/pleeease#32]
Hi,
I use node-sass/libsass with source maps enabled. The source map is correctly generated by libsass and the sourceMappingURL is appended to the file content.

Unfortunately pleeease removes the sourceMappingURL from the file though the `minifier` option is set to `false`.

I guess thats a bug and not intended?

This is my config file:
```
{
  "filters": true,
  "rem": true,
  "pseudoElements": true,
  "opacity": false,

  "import": true,
  "minifier": false,
  "mqpacker": false,

  "sourcemaps": false,

  "next": false
}
```

**Comment by iamvdo** [comment]
Hi, do you still have the bug ?

I've just released v3.0.0 that include node-sass directly. Maybe you can test ?

**Comment by iamvdo** [comment]
Just add to `.pleeeaserc`:

```javascript
{
    "sass": true
}
```

Oh, I've just seen that it doesn't appear in docs. :/

**Comment by christianseel** [comment]
This is what I just tried based on the pleeease docs:
```
// 'file' is the to-be-processed scss file
var outFile = params.outputDir + path.basename(file, path.extname(file)) + '.css';
		
		var css = fs.readFileSync(file, 'utf8');
		
		var pleeeaseOptions = {
    		"in": file,
    		"out": path.basename(file, path.extname(file)) + '.css',
    		sass: {
        		file: file,
        		outFile: path.resolve(outFile),
        		includePaths: [ 'assets/tpl/sources/scss/', 'assets/tpl/sources/', 'assets/tpl/sources/bower_components/' ],
                sourceMap: true,
    		},
    		"rem": true,
    		"autoprefixer": {"browsers": ['> 3%', 'last 2 versions', 'Firefox ESR', 'Opera 12.1', 'Explorer 9']},
    		"import": true,
            "minifier": true,
            "sourcemaps": true
		};
		
		var fixed = pleeease.process(css, pleeeaseOptions);
		
		fs.writeFile(outFile, fixed, function(err) {
		    if(err) {
		        console.log(color.red('Error saving ' + outFile + ': ' + err));
		    } else {
		        // file saved
		        console.log(color.green('Rendered CSS for '+file + ' to ' +outFile));
		    }
		});
```

It's not working as expected. I'd like to have the source maps *not* base64 included, but saved as an extra file. Also the included source map seems to broken, as Chrome is not showing the source files.

**Comment by iamvdo** [comment]
Sourcemaps are only base64 for the moment + specific sass options are not used. 
I'll explain a bit latter, I have to go for now :) I really want to hear your voice from this.

**Comment by iamvdo** [comment]
>I'd like to have the source maps not base64 included, but saved as an extra file

Use something like:

```javascript
{
    "sass": true,
    "sourcemaps": {
        "map": { "inline": false },
        "from": "input.css",
        "to": "output.css"
    }
}
```

When an object is pass to the `sourcemaps` option, it is use as-is for postcss options, so you could check PostCSS documentation. Now, when using the `process` method, you will get an object:

````javascript
var fixed = pleeease.process(css, pleeeaseOptions);

// fixed.css => css as string
// fixed.map => sourcemaps
```

>included source map seems to broken

The `from` and `to` are used to generates correct sourcemaps, not "in" and "out", nor sass specific options. I plan to use "in" and "out" option, as you tried, because it could be much simpler to understand.

It's still an experimental feature, so we need to clarify which options can be used and which cannot.

**Comment by christianseel** [comment]
I now have this config, but it's not really working:
```
pleeeaseOptions = {
    		"in": file,
    		"out": path.basename(file, path.extname(file)) + '.css',
    		sass: true,
    		"rem": true,
    		"autoprefixer": {"browsers": ['> 3%', 'last 2 versions', 'Firefox ESR', 'Opera 12.1', 'Explorer 9']},
    		"import": true,
            "minifier": true,
            "sourcemaps": {
                "map": { "inline": false },
                "from": file,
                "to": outFile
            }
		};
```

Seems like the bindings with the different imported scss files are incorrect and/or missing.

**Comment by iamvdo** [comment]
Do you have a reduce test case where it is incorrect ?

**Comment by iamvdo** [comment]
+ why the `out` and `sourcemaps.to` isn't the same file? Pleeease uses `out` first, unless what I've told you previously.

**Comment by christianseel** [comment]
I'll continue debugging tomorrow :)
Thanks so far for your support!

**Comment by christianseel** [comment]
@iamvdo I've set up a "reduced" test case here: https://github.com/christianseel/pleeease-sm
Just clone, `npm install` and then `npm run build`.

You can see that at least the path is incorrect: `../sources/sources/` (one `sources` too much). Maybe that's the source of all other issues too, otherwise there might be wrong bindings.

**Comment by iamvdo** [comment]
Hi. I came up with a solution to your problem. I made many changes so I will release next version on next week.
Problems are:
- Sourcemaps were not correctly generated (it's OK now)
- Minifier modifies previous Sass sourcemaps (still a bug to investigate, but less problematic)
- in `scss/_atoms.css` line 61, the character `»` fails sourcemaps
