### ISSUE TITLE
removes semi-colon

### ISSUE THREAD

**Issue by jayenashar** [iamvdo/pleeease#33]
.test {
        content: 'sample'; /* ok */
        content: 'sample'; /* removes semi-colon */
    }

removes semi-colon when it's the last declaration in the rule set and there's a comment after it.  becoming:

    .test {
        content: 'sample'; /* ok */
        content: 'sample' /* removes semi-colon */
    }

**Comment by iamvdo** [comment]
Hi,
This was a PostCSS issue, fixed in 3.0.6, postcss/postcss#136

Pleeease already uses this version, try to `npm update pleeease (-g)` ? Or maybe `npm uninstall pleeease` then `npm install pleeease`.

BTW, I need to update to PostCSS v4.x.x

**Comment by jayenashar** [comment]
I hit the issue on the demo site, pleeease.io/play
