### ISSUE TITLE
Feature Request: rem - automatic px value from body

### ISSUE THREAD

**Issue by owzim** [iamvdo/pleeease#36]
Since pleeease is using PostCSS anyway, it should be possible to get the body `font-size` and use it for calculations.

What do you think?

**Comment by iamvdo** [comment]
It's already OK (it uses [Pixrem](https://github.com/robwierzbowski/node-pixrem)), but I need to release next version to make it work. ;) I hope v3.0 will be OK this week.

**Comment by iamvdo** [comment]
Fixed
