### ISSUE TITLE
Path rewriting in url(../)

### ISSUE THREAD

**Issue by gavrochelegnou** [iamvdo/pleeease#37]
When i try to compile my file 
`/css/app.css`
to
`/css/app.min.css`
Every path in my file containing `url(../XYZ)` is rewriten as `url(XYZ)`
Ex. for :
`background:url(../img/test.png)` 
output is :
`background:url(img/test.png)`
The same goes for `font-face src` etc ...

I tried using a `.pleeeaserc` file and direct commands like this :
`pleeease compile css/app.css -t css/app.min.css`
But i got the same result.

Thanks a lot.

**Comment by oilvier** [comment]
Je rencontre le même problème sur la version 3.2.0.

**Comment by iamvdo** [comment]
Les URLs sont réécrites par rapport au fichier final, ce qui logique. Quel est ton problème ?

**Comment by oilvier** [comment]
Ah!
En fait je suis habitué à la version précédente de pleeease et visiblement le fonctionnement n'était pas le même.

Dans la même configuration de fichiers :
/build/_sprite.css
/images/sprite.png
screen.css

En 2.0, `background-image:url(../images/sprite.png);` déclaré dans "_sprite.css" fonctionnait sans problèmes dans le fichier final (screen.css).
En 3.2.0 il faut effectivement écrire `background-image:url(../../images/sprite.png);`.

A quoi est dû ce changement ? Ou alors le fonctionnement en 2.0 était un coup de bol ? :)

**Comment by iamvdo** [comment]
Euh, non, c'est censé toujours fonctionner. Sauf que l'URL est réécrite `background-image:url(images/sprite.png);`, car relative à `screen.css`.
En 2.0, ça fonctionnait parce que `../` n'avait peut-être aucun effet si tu étais à la racine de ton site ?
En aucun ca tu ne devrais écrire `background-image:url(../../images/sprite.png);` car ce n'est pas logique.

**Comment by oilvier** [comment]
Je corrige l'arbo que j'ai posté plus haut, voilà ce que j'ai : 

├css/
├─build/
├──_sprite.css
├─screen.css
├images/
├─sprite.png

`background-image:url(../../images/sprite.png);` est donc l'écriture logique si on se place dans "build/_sprite.css".
pleeease 3.2.0 retourne bien `background-image:url(../images/sprite.png);` dans screen.css ce qui est toujours logique.

Par contre, ce que je ne comprends pas, c'est pourquoi en 2.0 l'écriture `background-image:url(../images/sprite.png);` retournait le même chemin dans "screen.css".
Je testerais demain sur un autre poste ce que donne `background-image:url(../../images/sprite.png);` avec la version 2.0

**Comment by iamvdo** [comment]
A priori, depuis `screen.css`, il essaie de remonter d'un dossier mais étant déjà à la racine, il ne peut pas, donc continue avec `images/sprite.png` et trouve la ressource ?

**Comment by oilvier** [comment]
Je viens de regarder au boulot où je suis sur pleeease 2.0.0.

Si j'écris `background-image:url(../../images/sprite.png);` dans ma source (css/build/_sprite.css) il ressort de la même manière (`background-image:url(../../images/sprite.png);`) dans le fichier final (css/screen.css) et donc ça ne fonctionne pas.

Du coup, c'est un problème sur la version 2.0.0 et c'est la version 3.2.0 qui est dans le vrai, non ?

**Comment by iamvdo** [comment]
Oui c'est bien ça. :)

**Comment by oilvier** [comment]
Du coup ça ne sert à rien de corriger, autant que je mette à jour vers la 3.2.0 ?

Merci pour l'aide en tout cas !

**Comment by iamvdo** [comment]
Oui, à priori. ;)
Merci d'utiliser Pleeease.

**Comment by oilvier** [comment]
Je réouvre car je viens de constater que le comportement n'est pas le même lorsque l'on a l'option `"sass":true`.

Pour revenir à mon exemple :

> background-image:url(../../images/sprite.png); est donc l'écriture logique si on se place dans "build/_sprite.css".
> pleeease 3.2.0 retourne bien background-image:url(../images/sprite.png); dans screen.css ce qui est toujours logique.

Lorsqu'on a `"sass":true`, pleeease 3.3.0 retourne la même chose que dans le fichier source (`background-image:url(../../images/sprite.png);`) et le chemin ne fonctionne pas.

J'utilise pleeease-cli 3.2.8 et pleeease 3.3.0

**Comment by drublic** [comment]
I think I might have a similar issue but cannot read this thread though.

I don't want the rewrite to happen in my files. Is there an option to stop this rewrite?

**Comment by oilvier** [comment]
Summary in english of what has been said : 

* URL are rewrited based on the output file (since pleeease 3.2.0 at least).
* Apparently, when you use the option `"sass":true` in pleeease 3.3.0, the rewrite is inactive, possibly a bug. I wait for an answer on this.

In my knowledge, there's no option to opt-out of the rewrite.

**Comment by iamvdo** [comment]
>I don't want the rewrite to happen in my files. Is there an option to stop this rewrite?

@drublic Nope you can't. Why don't you want a rebase? Feel free to open another issue with a simple use case :)

**Comment by drublic** [comment]
@iamvdo We're using an npm module here. This one links an image like this:

    .some-sprite {
      background-image: url(sprite.png);
    }

I've set up a copy task for the images and they are now located as before right next to the css-file. Pleeease includes the full path to the node module. I now need to change my copy task to move the images to some fake directory which I usually would not need.

I will open another issue with this.
