### ISSUE TITLE
@import external URL error

### ISSUE THREAD

**Issue by andrejmlinarevic** [iamvdo/pleeease#40]
I seem to have found a bug related to using the @import directive in CSS with external URL. This is the import that is used. 

CSS import code: @import url(http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic);

Console log
![import bug](https://cloud.githubusercontent.com/assets/1894206/6150539/511069aa-b210-11e4-9d0b-7732d9a7c9c7.png)

**Comment by iamvdo** [comment]
Can you try to update pleeease and report if bug is still present. It was a bug in postcss-import that should be fixed now.

**Comment by andrejmlinarevic** [comment]
It works now, superb! Thanks for the update!
