### ISSUE TITLE
Cannot override features triggered by the autoprefixer's `browser` key

### ISSUE THREAD

**Issue by designorant** [iamvdo/pleeease#43]
As per @iamvdo's [comment](https://github.com/danielhusar/grunt-pleeease/issues/9#issuecomment-74831561), in Pleeease v3 you don't need to add options like `opacity: true` because they are enabled with the `autoprefixer` key. This is actually slightly misleading as the `autoprefixer` key should really be for Autoprefixer alone. The fact that you can specify the `browsers` array in two places now does not help either. I find that Pleeease tries to be a bit too clever here.

In my case, `filter: alpha(opacity=*)` breaks *a lot* of my Bootstrap theme in places that I have not even touched so it is very likely they will break default Bootstrap theme too.

I thought [specifying `opacity: false` will prevent Pleeease from injecting all those nasty filters in there](https://github.com/iamvdo/pleeease-website/blob/gh-pages/docs/index.html#L46) but that's not the case.

**Comment by iamvdo** [comment]
>  I find that pleeease tries to be a bit too clever here

Maybe, you're right. I assumed that if you need prefixes for specific versions, why would youdon't need fallbacks that target these versions ?

>This is actually slightly misleading as the autoprefixer key should really be for Autoprefixer alone

Right. Should we only use `browsers` for that ? Or is it better to always override with specific options ?

**Comment by designorant** [comment]
I would rather use terms like 'hacks' and 'polyfills' rather than 'fallbacks' when it comes to IE. It does not have anything to fall back to, and those hacks are huge performance hogs so they should not be thrown in all at once.

There is another, somewhat sketchy aspect to that. Do we want to make old browsers be just as the new ones? If so, why not throw [PIE](https://github.com/lojjic/PIE) in there? Why not add [Respond](https://github.com/scottjehl/Respond), [Selectivizr](https://github.com/keithclark/selectivizr) and a few others in there too? After all, we specified we target IE8. Fun fact here: I doubt there is anything that Autoprefixer does for IE8, actually. I may be wrong about that one, though.

I like the idea of Pleeease to be a bundle of tools/hacks/polyfils but it does need a simple on/off config to keep things in control.

Here is a screenshot of how Bootstrap modal looks with Pleeease's opacity in place:

![](http://i.imgur.com/B0YolxZ.png)

In this case Pleeease simply gets in the way and messes things up and there is no way to fix it without disabling IE8 support. What about double colon pseudo elements in that case?

**Comment by iamvdo** [comment]
Sorry for delay. Spent many days to get sourcemaps work from pre- to postprocessors.

You're absolutely right on this issue. Problem is this will break how app work, so I need to release 4.0. Before, I need to think to any possible other breaks, because I don't want to release 5.0 shortly after. :/

Is the app OK for you right now ? Do you find something weird or unclear at some points ?

**Comment by designorant** [comment]
Personally, I cannot see a reason why releasing one major version after another could be a problem as long as it is grounded from the semantic versioning perspective. I can see how managing minor fixes for two incompatible versions could introduce some unnecessary burden, though.

Either way, I have moved away from Pleeease as I needed that slightly more granular control. I am still a fan though. It certainly has its own audience so good luck!

**Comment by iamvdo** [comment]
Fixed in pleeease@4.0.0
