### ISSUE TITLE
"in" option is ignored in Windows

### ISSUE THREAD

**Issue by hteumeuleu** [iamvdo/pleeease#50]
I installed Pleeease on a client's PC today. It seems that in the latest Pleeease-cli version, the `in` option inside a configuration file is always ignored. I did a test with the following CSS files : 

* file1.css
* file2.css
* file3.css

And the following `.pleeeaserc` configuration file : 

 ```
{
  "in": ["file1.css"],
  "out": "output.css"
}
 ```

Running `please compile` in the command line then shows that `["file1.css", "file2.css", "file3.css"]` have been compiled. No matter what I tried, it seems that the `in` option in the configuration file is always ignored. 

The compilation works as intended to the `output.css` file if I use the command `pleeease compile "file1.css"`. I tried to invert the `in` and `out` declaration in the configuration file, with no success. 

Client's on a Windows 7 Pro SP1 (64 bits), using npm 2.7.4 with pleeease-cli 3.2.4 and pleeease 3.2.6. A colleague also confirmed tonight to have the same problem on his PC with the latest pleeease version.

**Comment by iamvdo** [comment]
Hey!
This should be fixed in iamvdo/pleeease-cli@3.2.5

Can you confirm ?

**Comment by hteumeuleu** [comment]
Yes ! Thanks a lot !
