### ISSUE TITLE
Add option to prevent automatic URL change for background-images

### ISSUE THREAD

**Issue by drublic** [iamvdo/pleeease#55]
When using urls as for example with background-images Pleeease currently changes the url to reflect some any compile-step. 

Sometimes this does not make sense to me which is why I think there should be an option to prevent this url update.

In certain cases you might want to maintain to url you set in your CSS file and not change it. This might the case if you copy images into certain directories or you optimize images automatically and move them through your build step.

Let's say you've a component `icon` which is located in folder `/components/icon/`.
Your CSS looks like this:

    .icon {
      background-image: url(sprite.svg);
    }

* There are four icons in the same directory but no sprite.svg.
* Your build step combines all icons into one sprite and moves it to your `/dist/` folder.
* Pleeease compiles CSS to `dist/` too.

Your compiled CSS now has an url like `components/icon/sprite.svg` which is not the correct path.
I don't want this to happen and want to turn off this feature.

Please let me know if I get something wrong or you need more information.

**Comment by iamvdo** [comment]
We need to add an option to make Pleeease not so clever. You're right.

**Comment by drublic** [comment]
Thank you!
