### ISSUE TITLE
Animation prefixing

### ISSUE THREAD

**Issue by getandyjones** [iamvdo/pleeease#56]
It semes that when running css through the prefixing tool, it doesn't recognise that 

animation: and @keyframes properties need prefixing.

Andy Jones

**Comment by iamvdo** [comment]
Can you share your setup? Which versions?

**Comment by getandyjones** [comment]
This is just using the tool directly on the web site
http://pleeease.io/play/  (ie copy and pasting css into the box)


Regards,

Andy

Visit our web site: http://www.tygamarketing.com
____________________________________________

Andy Jones
Creative Director
TYGA Marketing Limited
TYGA House, 13 Alban Park, Hatfield Road, St. Albans, Herts, AL4 0JJ
T: 01727 898 191  F: 01727 898 190
W: http://www.tygamarketing.com
____________________________________________

**Comment by iamvdo** [comment]
This works for me. Which browser?

**Comment by getandyjones** [comment]
Firefox on mac os x

Regards,

Andy

Visit our web site: http://www.tygamarketing.com
____________________________________________

Andy Jones
Creative Director
TYGA Marketing Limited
TYGA House, 13 Alban Park, Hatfield Road, St. Albans, Herts, AL4 0JJ
T: 01727 898 191  F: 01727 898 190
W: http://www.tygamarketing.com
____________________________________________

**Comment by getandyjones** [comment]
Actually - it's working when i type it in - but it didn't when I pasted the
css in.

V strange

Regards,

Andy

Visit our web site: http://www.tygamarketing.com
____________________________________________

Andy Jones
Creative Director
TYGA Marketing Limited
TYGA House, 13 Alban Park, Hatfield Road, St. Albans, Herts, AL4 0JJ
T: 01727 898 191  F: 01727 898 190
W: http://www.tygamarketing.com
____________________________________________

**Comment by iamvdo** [comment]
Can't reproduce on Firefox for Mac. You problem is elsewhere. :)
