### ISSUE TITLE
Error: CssSyntaxError: <css input>:1:1: Unknown word

### ISSUE THREAD

**Issue by p0stw3b** [iamvdo/pleeease#67]
test1.less

<pre>
<code>
// @import "components/buttons.less";
.b{color:#fff}
</code>
</pre>

<blockquote>pleeease compile test1.less</blockquote>

<blockquote>
 Compilation error
Error: CssSyntaxError: <css input>:1:1: Unknown word<br>
// @import "components/buttons.less";<br>
^
</blockquote>

<br>
test2.less

<pre>
<code>
//.top{
//  padding: 1.1rem 0;
//}
.top{
 padding: 1.1rem 0;
}
</code>
</pre>

<blockquote>pleeease compile test2.less</blockquote>

<blockquote>
 Compilation error
Error: CssSyntaxError: <css input>:2:5: Unknown word<br>
//.top{<br>
//  padding: 1.1rem 0;<br>
    ^<br>
//}<br>
</blockquote>

**Comment by iamvdo** [comment]
Does it work before pleeease@4.0.2 ?

**Comment by p0stw3b** [comment]
<blockquote>
[]# pleeease -V<br>
pleeease-cli 4.0.0<br>
pleeease     4.0.2<br>
</blockquote>

**Comment by iamvdo** [comment]
I think you're not using a `.pleeeaserc` file to enable LESS preprocessor. 
Maybe, I should add a detection of file extension. Will open an issue in pleeease-cli repo.
