### ISSUE TITLE
PostCSS Plugin

### ISSUE THREAD

**Issue by zslabs** [iamvdo/pleeease#71]
Can this be included as a PostCSS plugin instead of running everything through a separate pleeease instance? The normal way of including didn't work. It looks like pleeease uses the PostCSS API, but doesn't actually render itself as a plugin; unless I'm way off on how I understand this library works.

**Comment by iamvdo** [comment]
Yes, it whould work, see testcase: https://github.com/iamvdo/pleeease/blob/master/test/pleeease.js#L98-L103

> unless I'm way off on how I understand this library works.

Pleeease was the first postcss plugins pack. No more.
