### ISSUE TITLE
How do you stop a pleeease watch?

### ISSUE THREAD

**Issue by newjie** [iamvdo/pleeease#74]
I use pleeease on remote linux server. After I do "Pleeease watch“ via SSH it just keeps running no matter I close the SSH or close the terminal, which is good, because I don't have to worry about it anymore... until I wanna change what files to watch. 

I am not very familiar with Linux and I read through pleeease documentation it doesn't provide a way to stop the "watch" process.

**Comment by iamvdo** [comment]
There is no Pleeease's specific way to stop process. It's a classic one, so you need to find a solution like for any other process.
