### ISSUE TITLE
Changes background url property.

### ISSUE THREAD

**Issue by KingSora** [iamvdo/pleeease#81]
Hello!

I've found a bug:
If I've `background: url(../../img/picture.jpg)` set in my CSS, the tool changes it to 
`background: url(img/picture.jpg)`. This could be a feature but in my case it's simply a bug.

It would be a nice thing if this behavior could be configurated in the options.

Best regards,
Sora

**Comment by iamvdo** [comment]
This is an intended behavior. URLs are rebased according to your destination file (`out` option).
You can switch off by using `rebaseUrls: false` in options.
See http://pleeease.io/docs/#import and http://pleeease.io/docs/#rebaseurls

**Comment by KingSora** [comment]
Could you integrate the same option in this page: http://pleeease.io/play/ ?

**Comment by iamvdo** [comment]
Already this behavior. imports are not handled on http://pleeease.io/play/

**Comment by iamvdo** [comment]
Oh, I see, url in background. Sorry, will fix be asap.

**Comment by KingSora** [comment]
Thank you very much! :)

**Comment by iamvdo** [comment]
Done via https://github.com/iamvdo/pleeease-website/commit/bdf9889e0cae8189bdab20b60f5826230a6898d3
