### ISSUE TITLE
Compilation fails with sass indented syntax 

### ISSUE THREAD

**Issue by sheoak** [iamvdo/pleeease#90]
When using .scss format it works, but if I use .sass syntax with identation it fails.
Compiling directly with sass works.

_test.sass:_
```
body
  color: red
```

_.pleeeaserc:_
```
{
  "sass": true,
  "in": ["test.sass"],
  "out": "test.css"
}
```

```
$ pleeease compile
Pleeease Compilation error
Error: Error: Sass: parsing fails, Error: Invalid CSS after "b": expected 1 selector or at-rule, was "body"
```

```
$ sass --version
1.8.0 compiled with dart2js 2.0.0-dev.66.0
```

```
$ pacman -Q libsass
libsass 3.4.7-1
```

**Comment by iamvdo** [comment]
AFAIK, libsass supports sass syntax with `indentedSyntax` option. So you can set your `.pleeeaserc` file like this:
```json
{
  "sass": {
    "indentedSyntax": true
  },
  "in": ["test.sass"],
  "out": "test.css"
}
```

Sorry for lack of documentation

**Comment by sheoak** [comment]
Thank you! Is there a repository for updating the documentation?
